# Netlify deployment configuration for Biombo Web monorepo
# This configuration deploys the Astro frontend with SSR

[build]
  # Build command
  command = "pnpm install && pnpm run build"
  
  # Publish directory - relative to base
  publish = "dist"

[build.environment]
  # Node.js version for optimal performance and compatibility
  NODE_VERSION = "20"
  
  # Environment variables for production
  NODE_ENV = "production"
  
  # Enable Netlify Image CDN integration
  NETLIFY_USE_ASTRO = "true"
  
  # Astro-specific optimizations
  ASTRO_TELEMETRY_DISABLED = "1"

# The Astro Netlify adapter automatically handles functions
# No manual configuration needed here

# Headers for optimal performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # HSTS - Force HTTPS for 1 year, include subdomains
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Content Security Policy - Allows only trusted sources
    # Note: Adjusted to remove Google reCAPTCHA since it's been removed
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-src 'self';"

# Static asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML pages - shorter cache for dynamic content
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=31536000"

# API routes and SSR pages
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Font optimization
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Image optimization headers
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# The Netlify adapter handles all routing automatically for SSR
# No manual redirects needed

# Context-specific environment variables
[context.production.environment]
  NODE_ENV = "production"
  PUBLIC_ENV_MODE = "production"
  PUBLIC_SANITY_USE_CDN = "true"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  PUBLIC_ENV_MODE = "staging"
  PUBLIC_SANITY_USE_CDN = "false"
  
[context.branch-deploy.environment]
  NODE_ENV = "production"
  PUBLIC_ENV_MODE = "staging"
  PUBLIC_SANITY_USE_CDN = "false"